### PR TITLE
Change `window` to `globalThis` for Edge Runtime support

### PR DESCRIPTION
**Pull request by ConProgramming**
Support for Cloudflare Workers, Deno, and other WinterCG runtimes

### CODE REVIEW

**Comment by belladoreai** [comment]
Hey, thanks for pointing out this issue and thanks for making a PR to fix it! I'm not too familiar with these runtimes, but I think the PR needs some changes before it can be merged. Can you help me figure out what exactly needs to be changed?

As I understand it, `globalThis` is available in all runtimes. That means this `if` statement will always branch into returning `globalThis.atob(encodedString)`:

```
    if (typeof globalThis !== "undefined") return globalThis.atob(encodedString)
    return Buffer.from(encodedString, 'base64').toString('latin1')
```

If it is intentional to return `globalThis.atob(encodedString)` in all runtimes, then this `if` statement shouldn't exist at all. I'm not sure if that's what you meant to do? Should we just return it in all runtimes? The reason why I added this `if` statement was that the `atob` method was deprecated in Node, so I figured it would be "best practice" to do the base64 decoding in Node with a different method. Is this alternative method of base64 decoding causing some issues in the runtimes you mentioned?

**Comment by ConProgramming** [comment]
`Buffer` is a node only thing, so `atob` has to be used in other runtimes yes.

As for the if statement - my bad yes, the if will pass everywhere.

We could instead check if `Buffer` is available as the if statement, and make `globalThis.atob` the default.

**Comment by belladoreai** [comment]
> We could instead check if `Buffer` is available as the if statement, and make `globalThis.atob` the default.

This sounds like a good solution to me! Can you push the change and I will merge it?

**Comment by belladoreai** [comment]
I have now pushed a change that will use `atob` in all runtimes, even though it is deprecated in Node.

**Pull request closed without merging**
